### ISSUE TITLE
11.1.1版本在页面查看修改历史的时候返回500错误码

### ISSUE THREAD

**Issue by totobo** [twang2218/gitlab-ce-zh#70]
回退至11.0.3之后该功能正常。

错误信息如下
``` 
Started GET "/dev/Server/xcommon/commit/420c7e9b262a87cd115853069acd29ee6c6043e0" for 192.168.32.1 at 2018-08-01 05:50:51 +0000
Processing by Projects::CommitController#show as HTML
  Parameters: {"namespace_id"=>"dev/Server", "project_id"=>"xcommon", "id"=>"420c7e9b262a87cd115853069acd29ee6c6043e0"}
Completed 500 Internal Server Error in 156ms (ActiveRecord: 18.1ms)

SyntaxError (/opt/gitlab/embedded/service/gitlab-rails/app/views/shared/notes/_form.html.haml:45: syntax error, unexpected keyword_ensure, expecting end-of-input
          ensure
                ^):
  app/views/shared/notes/_form.html.haml:45: syntax error, unexpected keyword_ensure, expecting end-of-input
  app/views/shared/notes/_notes_with_form.html.haml:19:in `_app_views_shared_notes__notes_with_form_html_haml__2979402914983024036_70132423995660'
  app/views/projects/commit/show.html.haml:19:in `_app_views_projects_commit_show_html_haml__742081695966163421_70132248452160'
  app/controllers/projects/commit_controller.rb:25:in `block (2 levels) in show'
  app/controllers/projects/commit_controller.rb:24:in `show'
  lib/gitlab/i18n.rb:51:in `with_locale'
  lib/gitlab/i18n.rb:57:in `with_user_locale'
  app/controllers/application_controller.rb:362:in `set_locale'
  lib/gitlab/middleware/multipart.rb:97:in `call'
  lib/gitlab/request_profiler/middleware.rb:14:in `call'
  lib/gitlab/middleware/go.rb:17:in `call'
  lib/gitlab/etag_caching/middleware.rb:11:in `call'
  lib/gitlab/middleware/read_only/controller.rb:38:in `call'
  lib/gitlab/middleware/read_only.rb:16:in `call'
  lib/gitlab/request_context.rb:18:in `call'
  lib/gitlab/metrics/requests_rack_middleware.rb:27:in `call'
  lib/gitlab/middleware/release_env.rb:10:in `call'
```

**Comment by twang2218** [comment]
这个可能是翻译过程中造成的问题，上游汉化项目已经修复了：https://gitlab.com/xhang/gitlab/commit/abce88c33aaf18f06a2bce1529984b5d1d61c2e4

修复应该已经合并进 `11.1.2` 以及 `11.1.3`了，我已经更新了镜像。可以测试一下是否新版本的镜像已经修复了该问题。谢谢。

**Comment by totobo** [comment]
非常感谢，新版本测试无问题。
